# Generated by Django 5.1 on 2024-08-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
